server:
  port: 8020
  servlet:
    context-path: /shop

# datasource
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_springboot?createDatabaseIfNotExist=true&useSSL=true
    username: root
    password: Jerry@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Email service
  mail:
    host: smtp.gmail.com
    port: 587
    username: azilakujeremiah@gmail.com
    password: ${MAIL_SECRET}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  # JPA
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

  # multipart-file
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 100MB
      max-request-size: 100MB

  # Security
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 887617727653-btgm6o0tjbivq3rtrcjtqu1k9lgpmoms.apps.googleusercontent.com
            clientSecret: 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