server:
  port: 8019
  servlet:
    context-path: /admin

# Datasource
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_springboot?createDatabaseIfNotExist=true&useSSL=true
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Email service
  mail:
    host: smtp.gmail.com
    port: 587
    username: azilakujeremiah@gmail.com
    password: ${MAIL_SECRET}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  # JPA
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

  # Multipart file
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 100MB
      max-request-size: 100MB
