server:
  port: 8090

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/booking-service

# Eureka Client Configuration
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
