server:
  port: 8070

#Mongo data base configuration
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/user-service

# Eureka Client Configuration
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
